// game_stubs.cpp - Auto-generated stubs for game.asm symbols
// Generated by Open1560 build script
// Uses weak linkage to avoid conflicts with existing definitions

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"

// === Required Headers ===
// --- agi ---
#include "agi/cmodel8.h"
#include "agi/cmodelx.h"
#include "agi/dlp.h"
#include "agi/dlptmpl.h"
#include "agi/error.h"
#include "agi/getdlp.h"
#include "agi/lmodel.h"
#include "agi/mtldef.h"
#include "agi/palette.h"
#include "agi/pipeline.h"
#include "agi/surface.h"
#include "agi/texdef.h"
#include "agi/viewport.h"
// --- agirend ---
#include "agirend/bilight.h"
#include "agirend/bilmodel.h"
#include "agirend/lighter.h"
#include "agirend/projvtx.h"
#include "agirend/rdlp.h"
#include "agirend/surfrender.h"
#include "agirend/zbrender.h"
// --- agisw ---
#include "agisw/swrend.h"
#include "agisw/swrsys.h"
#include "agisw/swtexdef.h"
// --- agiworld ---
#include "agiworld/bone.h"
#include "agiworld/getmesh.h"
#include "agiworld/meshlight.h"
#include "agiworld/meshload.h"
#include "agiworld/meshrend.h"
#include "agiworld/meshset.h"
#include "agiworld/quality.h"
#include "agiworld/texsheet.h"
#include "agiworld/texsort.h"
// --- arts7 ---
#include "arts7/benchstats.h"
#include "arts7/camera.h"
#include "arts7/cullmgr.h"
#include "arts7/form.h"
#include "arts7/lamp.h"
#include "arts7/node.h"
#include "arts7/pgraph.h"
#include "arts7/sim.h"
// --- data7 ---
#include "data7/metatype.h"
#include "data7/str.h"
// --- dyna7 ---
#include "dyna7/dyna.h"
#include "dyna7/gfx.h"
// --- mmai ---
#include "mmai/aiGoalAvoidPlayer.h"
#include "mmai/aiGoalChase.h"
#include "mmai/aiGoalFollowWayPts.h"
#include "mmai/aiGoalStop.h"
#include "mmai/aiIntersection.h"
#include "mmai/aiMap.h"
#include "mmai/aiPath.h"
#include "mmai/aiPedestrian.h"
#include "mmai/aiRailSet.h"
#include "mmai/aiStuck.h"
#include "mmai/aiVehicle.h"
#include "mmai/aiVehicleAmbient.h"
#include "mmai/aiVehicleMGR.h"
#include "mmai/aiVehicleOpponent.h"
#include "mmai/aiVehiclePolice.h"
#include "mmai/aiVehicleSpline.h"
#include "mmai/aiaudiomanager.h"
// --- mmanim ---
#include "mmanim/AnimMgr.h"
#include "mmanim/bridge.h"
// --- mmaudio ---
#include "mmaudio/audstream.h"
#include "mmaudio/dsglobal.h"
#include "mmaudio/head.h"
#include "mmaudio/manager.h"
#include "mmaudio/mmvoicecommentary.h"
#include "mmaudio/sound.h"
// --- mmbangers ---
#include "mmbangers/active.h"
#include "mmbangers/banger.h"
#include "mmbangers/data.h"
// --- mmcamcs ---
#include "mmcamcs/basecamcs.h"
#include "mmcamcs/trackcamcs.h"
// --- mmcamtour ---
#include "mmcamtour/gamerecord.h"
// --- mmcar ---
#include "mmcar/car.h"
#include "mmcar/carmodel.h"
#include "mmcar/carsim.h"
#include "mmcar/carsimcheap.h"
#include "mmcar/shard.h"
#include "mmcar/skid.h"
#include "mmcar/surfaceaudioinfo.h"
#include "mmcar/trailer.h"
#include "mmcar/transmission.h"
#include "mmcar/wheel.h"
// --- mmcity ---
#include "mmcity/anim.h"
#include "mmcity/cellrend.h"
#include "mmcity/cullcity.h"
#include "mmcity/inst.h"
#include "mmcity/loader.h"
#include "mmcity/portal.h"
#include "mmcity/position.h"
#include "mmcity/positions.h"
#include "mmcity/renderweb.h"
// --- mmcityinfo ---
#include "mmcityinfo/cityinfo.h"
#include "mmcityinfo/citylist.h"
#include "mmcityinfo/miscdata.h"
#include "mmcityinfo/playercfg.h"
#include "mmcityinfo/playerdata.h"
#include "mmcityinfo/playerdir.h"
#include "mmcityinfo/racedata.h"
#include "mmcityinfo/state.h"
#include "mmcityinfo/vehinfo.h"
#include "mmcityinfo/vehlist.h"
// --- mmdyna ---
#include "mmdyna/bndtmpl.h"
#include "mmdyna/bndtmpl2.h"
#include "mmdyna/isect.h"
#include "mmdyna/poly.h"
// --- mmeffects ---
#include "mmeffects/birth.h"
#include "mmeffects/card2d.h"
#include "mmeffects/damage.h"
#include "mmeffects/linespark.h"
#include "mmeffects/meshform.h"
#include "mmeffects/mmtext.h"
// --- mmgame ---
#include "mmgame/cd.h"
#include "mmgame/dash.h"
#include "mmgame/game.h"
#include "mmgame/gameedit.h"
#include "mmgame/gameman.h"
#include "mmgame/gamemulti.h"
#include "mmgame/hud.h"
#include "mmgame/hudmap.h"
#include "mmgame/icons.h"
#include "mmgame/interface.h"
#include "mmgame/mmambientaudio.h"
#include "mmgame/multicr.h"
#include "mmgame/player.h"
#include "mmgame/popup.h"
#include "mmgame/waypoints.h"
#include "mmgame/wphud.h"
// --- mminput ---
#include "mminput/friction.h"
#include "mminput/input.h"
#include "mminput/joystick.h"
#include "mminput/localize.h"
// --- mmnetwork ---
#include "mmnetwork/netobject.h"
#include "mmnetwork/network.h"
// --- mmphysics ---
#include "mmphysics/inertia.h"
#include "mmphysics/joint3dof.h"
#include "mmphysics/osample.h"
#include "mmphysics/phys.h"
// --- mmui ---
#include "mmui/pu_control.h"
#include "mmui/pu_menu.h"
#include "mmui/pu_results.h"
#include "mmui/racebase.h"
// --- mmwidget ---
#include "mmwidget/button.h"
#include "mmwidget/compscroll.h"
#include "mmwidget/dropdown.h"
#include "mmwidget/manager.h"
#include "mmwidget/menu.h"
#include "mmwidget/mstore.h"
#include "mmwidget/navbar.h"
// --- vector7 ---
#include "vector7/geomath.h"
#include "vector7/matrix34.h"
#include "vector7/matrix44.h"
#include "vector7/randmath.h"
#include "vector7/vector2.h"
#include "vector7/vector3.h"

// === Data Stubs (Weak) ===

__attribute__((weak)) aiAudioManager* AIAUDMGRPTR {};
__attribute__((weak)) aiMap AIMAP {};
__attribute__((weak)) AudManager* AUDMGRPTR {};
__attribute__((weak)) b32 AnnotateTextures {};
__attribute__((weak)) mmBangerData* BangerProjectile {};
__attribute__((weak)) i32 BenchOSample {};
__attribute__((weak)) f32 BoneScale {};
__attribute__((weak)) i32 BoundBytesPaged {};
__attribute__((weak)) i32 BoundsPaged {};
__attribute__((weak)) i32 CHEATING {};
__attribute__((weak)) i32 CHICAGO {};
__attribute__((weak)) mmCityList* CityListPtr {};
__attribute__((weak)) Vector3 ColBlue {};
__attribute__((weak)) Vector3 ColGreen {};
__attribute__((weak)) Vector3 ColLightCyan {};
__attribute__((weak)) Vector3 ColOrange {};
__attribute__((weak)) Vector3 ColPurple {};
__attribute__((weak)) Vector3 ColRed {};
__attribute__((weak)) Vector3 ColYellow {};
__attribute__((weak)) agiColorModelABGR ColorModelABGR {};
__attribute__((weak)) agiColorModelARGB ColorModelARGB {};
__attribute__((weak)) agiColorModelRGB555 ColorModelRGB555 {};
__attribute__((weak)) agiColorModelRGB555_Rev ColorModelRGB555_Rev {};
__attribute__((weak)) agiColorModelRGB565 ColorModelRGB565 {};
__attribute__((weak)) agiColorModelRGB565_Rev ColorModelRGB565_Rev {};
__attribute__((weak)) agiColorModelRGB888 ColorModelRGB888 {};
__attribute__((weak)) agiColorModelRGB888_Rev ColorModelRGB888_Rev {};
__attribute__((weak)) agiColorModelRGBA4444 ColorModelRGBA4444 {};
__attribute__((weak)) agiColorModelRGBA5551 ColorModelRGBA5551 {};
__attribute__((weak)) HashTable DLPTemplateHash {};
__attribute__((weak)) DSGlobal* DSGlobalPtr {};
__attribute__((weak)) i32 DebugMemory {};
__attribute__((weak)) f32 DepthOffset {};
__attribute__((weak)) f32 DepthScale {};
__attribute__((weak)) b32 DontClearPositions {};
__attribute__((weak)) i32 DynaDrawMode {};
__attribute__((weak)) f32 EggFriction {};
__attribute__((weak)) i32 EnableCachedPoly {};
__attribute__((weak)) i32 EnableTexSorting {};
__attribute__((weak)) i32 EnvMapFlushes {};
__attribute__((weak)) mmInput* GameInputPtr {};
__attribute__((weak)) f32 HitWaterTimer {};
__attribute__((weak)) mmIODev* IODev {};
__attribute__((weak)) i32 InputConfiguration {};
__attribute__((weak)) i32 IsSnowing {};
__attribute__((weak)) extern char LocPlayerName {};
__attribute__((weak)) char* LocStrButton {};
__attribute__((weak)) char* LocStrJoystick {};
__attribute__((weak)) char* LocStrUndef {};
// UNPARSED DATA: [vector7/randmath.h] ARTS_IMPORT extern void (*LogRandomCalls)(void);
__attribute__((weak)) mmPlayerData MMCURRPLAYER {};
__attribute__((weak)) mmStatePack MMSTATE {};
__attribute__((weak)) Stream* MakeTableStats {};
__attribute__((weak)) f32 MaxCardSize {};
__attribute__((weak)) i32 MeshBytesPaged {};
__attribute__((weak)) char* MeshCurrentObject {};
__attribute__((weak)) i32 MeshesPaged {};
__attribute__((weak)) f32 MinCardSize {};
__attribute__((weak)) asNetwork NETMGR {};
__attribute__((weak)) Vector3 ORIGIN {};
__attribute__((weak)) asPerfGraph* PGRAPH {};
// UNPARSED DATA: [agi/pipeline.h] ARTS_IMPORT extern void (*PROBER)(void*);
__attribute__((weak)) i32 PackShift {};
__attribute__((weak)) f32 ParticleMultiplier {};
__attribute__((weak)) Vector3 PlayerPos {};
__attribute__((weak)) i32 PopupEnabled {};
__attribute__((weak)) Vector3 ProjectileV {};
__attribute__((weak)) f32 ProjectileY {};
__attribute__((weak)) agiStats STATS {};
__attribute__((weak)) f32 ScreenClearY {};
__attribute__((weak)) u32 ShadowColor {};
__attribute__((weak)) Stream* StaticLog {};
__attribute__((weak)) agiTexSheet TEXSHEET {};
__attribute__((weak)) i32 TexBytesPaged {};
__attribute__((weak)) aconst char* TexSearchPath {};
__attribute__((weak)) i32 TexsPaged {};
__attribute__((weak)) aconst char* TextureSuffix {};
__attribute__((weak)) f32 Update3D {};
__attribute__((weak)) i32 UseDIKey {};
__attribute__((weak)) i32 UsePixelFog {};
__attribute__((weak)) HashTable VehicleDataHash {};
__attribute__((weak)) mmVehList* VehicleListPtr {};
__attribute__((weak)) Vector3 XAXIS {};
__attribute__((weak)) Vector3 YAXIS {};
__attribute__((weak)) Vector3 ZAXIS {};
__attribute__((weak)) i32 ZTrick {};
__attribute__((weak)) f32 _fAmbientUpdate {};
__attribute__((weak)) f32 _fCopUpdate {};
__attribute__((weak)) f32 _fOppUpdate {};
__attribute__((weak)) f32 _fPedUpdate {};
__attribute__((weak)) f32 _fTotUpdate {};
__attribute__((weak)) i32 _nAmbientQty {};
__attribute__((weak)) i32 _nPedQty {};
__attribute__((weak)) ulong agiBeginFrame {};
__attribute__((weak)) ulong agiBeginScene {};
__attribute__((weak)) i32 agiBitmapCount {};
__attribute__((weak)) i32 agiBitmapPixels {};
__attribute__((weak)) ulong agiClearViewport {};
__attribute__((weak)) ulong agiClipTimer {};
__attribute__((weak)) ulong agiCopyBitmap {};
__attribute__((weak)) char agiEnableZBuffer {};
__attribute__((weak)) ulong agiEndFrame {};
__attribute__((weak)) ulong agiEndScene {};
__attribute__((weak)) ulong agiFirstPass {};
__attribute__((weak)) ulong agiInvertTimer {};
__attribute__((weak)) ulong agiLightTimer {};
__attribute__((weak)) Vector3 agiMeshLighterAmbient {};
__attribute__((weak)) Vector3 agiMeshLighterFill1 {};
__attribute__((weak)) Vector3 agiMeshLighterFill1Color {};
__attribute__((weak)) Vector3 agiMeshLighterFill2 {};
__attribute__((weak)) Vector3 agiMeshLighterFill2Color {};
__attribute__((weak)) Vector3 agiMeshLighterSun {};
__attribute__((weak)) Vector3 agiMeshLighterSunColor {};
__attribute__((weak)) agiPalette agiPal {};
__attribute__((weak)) agiWorldRenderQuality agiRQ {};
__attribute__((weak)) ulong agiRasterization {};
__attribute__((weak)) ulong agiSecondPass {};
__attribute__((weak)) ulong agiStateChanges {};
__attribute__((weak)) ulong agiTransformTimer {};
__attribute__((weak)) ulong agiTraverseTimer {};
__attribute__((weak)) i32 agiVerbose {};
__attribute__((weak)) i32 debugTri {};
__attribute__((weak)) f32 defmass {};
__attribute__((weak)) i32 gRandSeed {};
__attribute__((weak)) extern lutQentry lutQ {};
__attribute__((weak)) i32 masscycle {};
__attribute__((weak)) void* myFont {};
__attribute__((weak)) u32 swActualScreenStride {};
__attribute__((weak)) i32 swBlueMask {};
__attribute__((weak)) i32 swBytesPerPixel {};
__attribute__((weak)) u16* swDepthBuffer {};
__attribute__((weak)) i32 swFbHeight {};
__attribute__((weak)) i32 swFbWidth {};
__attribute__((weak)) u32 swFrameOffset {};
__attribute__((weak)) i32 swGreenMask {};
__attribute__((weak)) i32 swIsInterlaced {};
__attribute__((weak)) i32 swRedMask {};
__attribute__((weak)) void* swScreen {};
__attribute__((weak)) u32 swScreenStride {};

// === Free Function Stubs (Weak) ===

__attribute__((weak)) LocString* AngelReadKeyString(u32 arg1) { return {}; }
__attribute__((weak)) void CheckLibraries() {}
__attribute__((weak)) void DeactivateApplication() {}
__attribute__((weak)) void DecodeDIErrorMFlag(ilong arg1) {}
__attribute__((weak)) void DrawBegin(aconst Matrix34& arg1) {}
__attribute__((weak)) void DrawColor(aconst Vector3& arg1) {}
__attribute__((weak)) void DrawEnd() {}
__attribute__((weak)) void DrawLabelf(Vector3& arg1, aconst char* arg2, ...) {}
// UNPARSED FUNC: [agirend/surfrender.h] ARTS_IMPORT void DrawLine(i32 arg1, i32 arg2) override;
// UNPARSED FUNC: [agirend/surfrender.h] ARTS_IMPORT void DrawLine(i32 arg1, i32 arg2) override;
__attribute__((weak)) void DumpPositions(aconst char* arg1) {}
// UNPARSED FUNC: [vector7/geomath.h] ARTS_IMPORT void GetBoundInfo(
__attribute__((weak)) DLPTemplate* GetDLPTemplate(char* arg1) { return {}; }
// UNPARSED FUNC: [agiworld/getmesh.h] ARTS_IMPORT agiMeshSet* GetMeshSet(aconst char* name, aconst char* group, Vector3* offset = nullptr,
__attribute__((weak)) asSparkLut* GetSparkLut(aconst char* path) { return {}; }
__attribute__((weak)) void LoadPositions(aconst char* arg1) {}
__attribute__((weak)) void RestoreApplication() {}
__attribute__((weak)) void SetClearSurfaceAudioInfos() {}
__attribute__((weak)) void SetRainSurfaceAudioInfos() {}
__attribute__((weak)) void SetSnowSurfaceAudioInfos() {}
__attribute__((weak)) void agiConeLighter(u8* arg1, u32* arg2, u32* arg3, agiMeshSet* arg4) {}
__attribute__((weak)) void agiMeshLighterQuarter(u8* arg1, u32* arg2, u32* arg3, agiMeshSet* arg4) {}
__attribute__((weak)) f32 frand() { return {}; }
__attribute__((weak)) void swInit() {}
__attribute__((weak)) void swLineInt(i32 start_x, i32 start_y, i32 end_x, i32 end_y, i32 color) {}
__attribute__((weak)) void swPoly(agiScreenVtx* arg1, i32 arg2) {}
__attribute__((weak)) void swQuad(agiScreenVtx* arg1, agiScreenVtx* arg2, agiScreenVtx* arg3, agiScreenVtx* arg4) {}
__attribute__((weak)) void swSetInterlace(i32 arg1) {}
__attribute__((weak)) void swTri(agiScreenVtx* arg1, agiScreenVtx* arg2, agiScreenVtx* arg3) {}

// === Class Member Stubs (Weak) ===

// --- AudHead ---
__attribute__((weak)) AudHead::AudHead(Matrix34* arg1) {}
__attribute__((weak)) i32 AudHead::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void AudHead::SetDoppler(f32 arg1) {}
__attribute__((weak)) void AudHead::SetRolloff(f32 arg1) {}
// --- AudManager ---
__attribute__((weak)) u32 AudManager::AlwaysEAX(u32 arg1) { return {}; }
__attribute__((weak)) void AudManager::AssignCDVolume(f32 arg1) {}
__attribute__((weak)) void AudManager::AssignWaveVolume(f32 arg1) {}
__attribute__((weak)) AudManager::~AudManager() {}
__attribute__((weak)) AudManager::AudManager() {}
__attribute__((weak)) u8 AudManager::CheckCDFile(aconst char* arg1) { return {}; }
__attribute__((weak)) void AudManager::DeallocateUIADF() {}
__attribute__((weak)) void AudManager::Disable(i16 sfx_mode, i16 cd_mode) {}
__attribute__((weak)) u32 AudManager::EAXEnabled() { return {}; }
__attribute__((weak)) void AudManager::Enable(char* arg1, i16 arg2, i16 arg3) {}
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetCDMusicOnMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetCommentaryOnMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetDSound3DMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetHiResMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetHiSampleSizeMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetSoundFXOnMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetStereoOnMask();
// UNPARSED MEMBER: [mmaudio/dsglobal.h] ARTS_IMPORT static const u32 GetUsingEAXMask();
__attribute__((weak)) mmVoiceCommentary* AudManager::GetVoiceCommentaryPtr() { return {}; }
__attribute__((weak)) i32 AudManager::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) i32 AudManager::PlayCDTrack(i32 track, b32 restart) { return {}; }
__attribute__((weak)) i32 AudManager::PlayCDTrack(i32 track, b32 restart) { return {}; }
__attribute__((weak)) void AudManager::SetBitDepthAndSampleRate(i32 arg1, ulong arg2) {}
__attribute__((weak)) void AudManager::SetCDPlayMode(u8 arg1) {}
__attribute__((weak)) i32 AudManager::SetEAXPreset(EAX_REVERBPROPERTIES* arg1) { return {}; }
__attribute__((weak)) void AudManager::SetNumChannels(i32 arg1) {}
__attribute__((weak)) void AudManager::SetVoiceCommentaryPtr(mmVoiceCommentary* arg1) {}
__attribute__((weak)) void AudManager::StopCD() {}
// --- AudSound ---
__attribute__((weak)) AudSound::~AudSound() {}
__attribute__((weak)) i32 AudSound::IsPlaying() { return {}; }
__attribute__((weak)) void AudSound::PlayOnce(char* arg1, f32 arg2, f32 arg3) {}
__attribute__((weak)) void AudSound::Stop() {}
// --- Bank ---
// UNPARSED MEMBER: [mmwidget/menu.h] ARTS_IMPORT UIToggleButton* AddToggle(i32 arg1, LocString* arg2, i32* arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7,
// --- BaseCamCS ---
__attribute__((weak)) void BaseCamCS::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void BaseCamCS::AfterLoad() {}
__attribute__((weak)) void BaseCamCS::ForceMatrixDelta(const Vector3& arg1) {}
__attribute__((weak)) MetaClass* BaseCamCS::GetClass() { return {}; }
// --- Card2D ---
__attribute__((weak)) void Card2D::SetDimensions(f32 x, f32 y, f32 w, f32 h) {}
// --- DLPTemplate ---
__attribute__((weak)) i32 DLPTemplate::BoundBox(Vector3& arg1, Vector3& arg2, aconst char* arg3) { return {}; }
__attribute__((weak)) i32 DLPTemplate::GetCentroid(Vector3& arg1, aconst char* arg2) { return {}; }
__attribute__((weak)) i32 DLPTemplate::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) i32 DLPTemplate::Release() { return {}; }
// --- DSGlobal ---
__attribute__((weak)) char** DSGlobal::GetDeviceNames() { return {}; }
// --- Joint3Dof ---
__attribute__((weak)) void Joint3Dof::BreakJoint() {}
__attribute__((weak)) void Joint3Dof::InitJoint3Dof(asInertialCS* arg1, const Vector3& arg2, asInertialCS* arg3, const Vector3& arg4) {}
__attribute__((weak)) void Joint3Dof::Reset() {}
__attribute__((weak)) void Joint3Dof::UnbreakJoint() {}
// --- MArray ---
__attribute__((weak)) void MArray::AddMenuData(i32 arg1, Vector4& arg2, char* arg3) {}
// --- Matrix34 ---
__attribute__((weak)) i32 Matrix34::Approach(const Matrix34& arg1, f32 arg2, f32 arg3, f32 arg4) { return {}; }
__attribute__((weak)) void Matrix34::Dot(const Matrix34& arg1, const Matrix34& arg2) {}
__attribute__((weak)) void Matrix34::FastInverse(const Matrix34& arg1) {}
__attribute__((weak)) void Matrix34::FromEulers(const Vector3& arg1) {}
__attribute__((weak)) Vector3 Matrix34::GetEulers() { return {}; }
__attribute__((weak)) void Matrix34::PolarView(const Vector4& arg1) {}
__attribute__((weak)) void Matrix34::RotateAbs(const Vector3& arg1, f32 arg2) {}
__attribute__((weak)) void Matrix34::Rotate(const Vector3& arg1, f32 arg2) {}
// --- Matrix44 ---
__attribute__((weak)) Matrix44::Matrix44(const Matrix34& arg1) {}
__attribute__((weak)) Matrix44::Matrix44(const Matrix34& arg1) {}
// --- MenuManager ---
__attribute__((weak)) void MenuManager::CheckBG(UIMenu* arg1) {}
__attribute__((weak)) void MenuManager::DisablePU() {}
__attribute__((weak)) i32 MenuManager::FindMenu(i32 idm) { return {}; }
__attribute__((weak)) void* MenuManager::GetFont(i32 arg1) { return {}; }
__attribute__((weak)) MenuManager* MenuManager::Instance {};
__attribute__((weak)) MenuManager::~MenuManager() {}
__attribute__((weak)) void MenuManager::PlayMenuSwitchSound() {}
__attribute__((weak)) b32 MenuManager::ScanGlobalKeys(i32 arg1) { return {}; }
// --- PUControl ---
__attribute__((weak)) PUControl::~PUControl() {}
// --- PUMenuBase ---
__attribute__((weak)) f32 PUMenuBase::AddExit(f32 arg1, f32 arg2, f32 arg3, f32 arg4) { return {}; }
__attribute__((weak)) RcOwner<agiBitmap> PUMenuBase::CreateDummyBitmap() { return {}; }
__attribute__((weak)) f32 PUMenuBase::CreateTitle() { return {}; }
__attribute__((weak)) void PUMenuBase::DisableExit() {}
__attribute__((weak)) PUMenuBase::~PUMenuBase() {}
__attribute__((weak)) i32 PUMenuBase::Update() { return {}; }
// --- PUResults ---
__attribute__((weak)) void PUResults::AddTitle(LocString* arg1, LocString* arg2) {}
__attribute__((weak)) void PUResults::Init320() {}
__attribute__((weak)) void PUResults::Reset() {}
// --- RDLP ---
__attribute__((weak)) RDLP::RDLP(agiPipeline* arg1) {}
// --- RaceMenuBase ---
__attribute__((weak)) RaceMenuBase::~RaceMenuBase() {}
// --- RadialGauge ---
__attribute__((weak)) i32 RadialGauge::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- TrackCamCS ---
__attribute__((weak)) TrackCamCS::~TrackCamCS() {}
// --- UICWArray ---
__attribute__((weak)) void UICWArray::Redraw() {}
// --- UIMenu ---
// UNPARSED MEMBER: [mmwidget/menu.h] ARTS_IMPORT UIBMButton* AddBMButton(i32 idc, aconst char* name, f32 x, f32 y, i32 type, Callback cb_1 = nullptr,
// UNPARSED MEMBER: [mmwidget/menu.h] ARTS_IMPORT UIButton* AddButton(
// UNPARSED MEMBER: [mmwidget/menu.h] ARTS_IMPORT uiWidget* AddHotSpot(
__attribute__((weak)) uiWidget* UIMenu::MouseHitCheck(i32 arg1, f32 arg2, f32 arg3) { return {}; }
__attribute__((weak)) void UIMenu::SetBstate(i32 index) {}
__attribute__((weak)) void UIMenu::SetFocusWidget(i32 arg1) {}
__attribute__((weak)) void UIMenu::SetSelected() {}
__attribute__((weak)) f32 UIMenu::UI_LEFT_MARGIN {};
__attribute__((weak)) UIMenu::~UIMenu() {}
__attribute__((weak)) UIMenu::UIMenu() {}
__attribute__((weak)) i32 UIMenu::Update() { return {}; }
// --- Vector2 ---
__attribute__((weak)) f32 Vector2::InvMag() { return {}; }
// --- Vector3 ---
__attribute__((weak)) f32 Vector3::Dist(const Vector3& arg1) { return {}; }
__attribute__((weak)) f32 Vector3::InvMag() { return {}; }
__attribute__((weak)) f32 Vector3::Mag() { return {}; }
// --- agiBILight ---
__attribute__((weak)) agiBILight::agiBILight(agiPipeline* arg1) {}
// --- agiBILightModel ---
__attribute__((weak)) agiBILightModel::agiBILightModel(agiPipeline* arg1) {}
// --- agiColorModel8 ---
__attribute__((weak)) agiColorModel8::agiColorModel8(agiPalette* arg1) {}
// --- agiLighter ---
// UNPARSED MEMBER: [agirend/lighter.h] ARTS_IMPORT static void BeginScene();
// --- agiMeshCardInfo ---
__attribute__((weak)) i32 agiMeshCardInfo::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- agiMeshSet ---
// UNPARSED STATIC: [agiworld/meshset.h] ARTS_IMPORT static agiMeshCardVertex DefaultQuad[4];
__attribute__((weak)) void agiMeshSet::EndGfx() {}
__attribute__((weak)) void agiMeshSet::EnvMap(Matrix34& arg1, agiTexDef* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_noUV_CPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_noUV_CPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_noUV_noCPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_noUV_noCPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_UV_CPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_UV_CPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_UV_noCPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_HW_UV_noCPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_noUV_CPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_noUV_CPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_noUV_noCPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_noUV_noCPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_UV_CPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_UV_CPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_UV_noCPV_DYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
__attribute__((weak)) void agiMeshSet::FirstPass_SW_UV_noCPV_noDYNTEX(u32* arg1, Vector2* arg2, u32 arg3) {}
// UNPARSED MEMBER: [agiworld/meshset.h] ARTS_IMPORT static void InitCards(agiMeshCardInfo& arg1);
__attribute__((weak)) i32 agiMeshSet::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// UNPARSED MEMBER: [agiworld/meshset.h] ARTS_IMPORT static void InitLocalize();
// UNPARSED MEMBER: [agiworld/meshset.h] ARTS_IMPORT static void LocalizeDirection(Vector3& arg1, Vector3& arg2);
__attribute__((weak)) void agiMeshSet::MultiTexEnvMap(u32* arg1, u32 arg2, agiTexDef* arg3, Matrix34& arg4) {}
// UNPARSED MEMBER: [agiworld/meshset.h] ARTS_IMPORT static void ARTS_FASTCALL ShadowInit(const Vector4& arg1, const Vector3& arg2);
// --- agiMonoLighter ---
__attribute__((weak)) agiMonoLighter::agiMonoLighter() {}
// --- agiMtlParameters ---
__attribute__((weak)) agiMtlParameters::agiMtlParameters() {}
__attribute__((weak)) void agiMtlParameters::Load(Stream* arg1) {}
// --- agiPhysParameters ---
__attribute__((weak)) void agiPhysParameters::Load(Stream* arg1) {}
// --- agiPipeline ---
__attribute__((weak)) agiPipeline* agiPipeline::CurrentPipe {};
__attribute__((weak)) agiRenderer* agiPipeline::CurrentRenderer {};
__attribute__((weak)) RcOwner<agiTexLut> agiPipeline::GetTexLut(aconst char* arg1) { return {}; }
// --- agiPolySet ---
__attribute__((weak)) i32 agiPolySet::TriCount {};
// --- agiProjVtx ---
__attribute__((weak)) i32 agiProjVtx::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- agiRGBLighter ---
__attribute__((weak)) agiRGBLighter::agiRGBLighter() {}
// --- agiSWRasterizer ---
__attribute__((weak)) agiSWRasterizer::agiSWRasterizer(agiPipeline* arg1) {}
__attribute__((weak)) void agiSWRasterizer::Card(i32 arg1, i32 arg2) {}
__attribute__((weak)) void agiSWRasterizer::Quad(i32 arg1, i32 arg2, i32 arg3, i32 arg4) {}
__attribute__((weak)) void agiSWRasterizer::Triangle(i32 arg1, i32 arg2, i32 arg3) {}
__attribute__((weak)) void agiSWRasterizer::Verts(agiVtx* arg1, i32 arg2) {}
// --- agiSWTexDef ---
__attribute__((weak)) b32 agiSWTexDef::IsAvailable() { return {}; }
__attribute__((weak)) void agiSWTexDef::Lock() {}
__attribute__((weak)) void agiSWTexDef::Request() {}
__attribute__((weak)) void agiSWTexDef::Set(Vector2& arg1, Vector2& arg2) {}
// --- agiSurfRenderer ---
__attribute__((weak)) void agiSurfRenderer::DrawCard(Vector3& arg1) {}
__attribute__((weak)) void agiSurfRenderer::Draw(DLP* arg1, i32 arg2) {}
__attribute__((weak)) void agiSurfRenderer::DrawLabel(agiVtx& arg1, char* arg2) {}
__attribute__((weak)) void agiSurfRenderer::DrawLine(i32 arg1, i32 arg2) {}
__attribute__((weak)) void agiSurfRenderer::DrawTri(i32 arg1, i32 arg2, i32 arg3) {}
__attribute__((weak)) void agiSurfRenderer::EndDraw() {}
__attribute__((weak)) void agiSurfRenderer::Points(agiVtx* arg1, i32 arg2) {}
__attribute__((weak)) i32 agiSurfRenderer::SurfaceCount {};
__attribute__((weak)) i32 agiSurfRenderer::VertexCount {};
__attribute__((weak)) void agiSurfRenderer::Verts(agiVtx* arg1, i32 arg2) {}
// --- agiSurfaceDesc ---
__attribute__((weak)) void agiSurfaceDesc::Load(Stream* arg1) {}
__attribute__((weak)) void agiSurfaceDesc::Reload(aconst char* arg1, aconst char* arg2, i32 arg3, i32 arg4, Stream* arg5, i32 arg6, i32 arg7) {}
// --- agiTexSheet ---
__attribute__((weak)) i32 agiTexSheet::GetVariationCount(aconst char* arg1) { return {}; }
__attribute__((weak)) void agiTexSheet::Kill() {}
__attribute__((weak)) void agiTexSheet::Load(Stream* arg1) {}
__attribute__((weak)) agiTexProp* agiTexSheet::Lookup(aconst char* name, i32 variation = 0) { return {}; }
__attribute__((weak)) char* agiTexSheet::RemapName(aconst char* arg1, i32 arg2) { return {}; }
// --- agiTexSorter ---
__attribute__((weak)) i32 agiTexSorter::AlphaSetCount {};
__attribute__((weak)) i32 agiTexSorter::BigPoolFlushes {};
// UNPARSED MEMBER: [agiworld/texsort.h] ARTS_IMPORT static void DoTexture(agiPolySet* arg1);
__attribute__((weak)) agiPolySet agiTexSorter::EnvPolySet {};
__attribute__((weak)) agiTexSorter* agiTexSorter::Instance {};
__attribute__((weak)) i32 agiTexSorter::MaxAlphaSetCount {};
__attribute__((weak)) i32 agiTexSorter::MaxIndicesPerSet {};
__attribute__((weak)) i32 agiTexSorter::MaxOpaqueSetCount {};
__attribute__((weak)) i32 agiTexSorter::MaxVertsPerSet {};
__attribute__((weak)) i32 agiTexSorter::OpaqueSetCount {};
__attribute__((weak)) i32 agiTexSorter::OutOfPoolFlushes {};
__attribute__((weak)) i32 agiTexSorter::OverflowFlushes {};
// --- agiViewParameters ---
__attribute__((weak)) agiViewParameters::agiViewParameters() {}
__attribute__((weak)) u32 agiViewParameters::MtxSerial {};
__attribute__((weak)) u32 agiViewParameters::ViewSerial {};
// --- agiViewport ---
__attribute__((weak)) agiViewport* agiViewport::Active {};
// --- agiZBufRenderer ---
__attribute__((weak)) agiZBufRenderer::agiZBufRenderer(agiRasterizer* arg1) {}
// --- aiAudioManager ---
__attribute__((weak)) void aiAudioManager::LoadCopVoice() {}
__attribute__((weak)) void aiAudioManager::RemoveVehicle(aiVehicleAmbient* arg1, i16 arg2) {}
// --- aiGoalChase ---
__attribute__((weak)) void aiGoalChase::CalcSpeed(f32 arg1) {}
// --- aiGoalFollowWayPts ---
__attribute__((weak)) aiGoalFollowWayPts::~aiGoalFollowWayPts() {}
__attribute__((weak)) aiGoalFollowWayPts::aiGoalFollowWayPts() {}
__attribute__((weak)) void aiGoalFollowWayPts::AvoidCollision(i32 dist_to_side) {}
__attribute__((weak)) void aiGoalFollowWayPts::AvoidOpponentCollision(aiVehicleOpponent* arg1) {}
__attribute__((weak)) i32 aiGoalFollowWayPts::DetectCollision(i32* arg1) { return {}; }
__attribute__((weak)) aiVehicleOpponent* aiGoalFollowWayPts::DetectOpponentCollision() { return {}; }
__attribute__((weak)) aiPath* aiGoalFollowWayPts::DetRdSegBetweenInts(aiIntersection* arg1, aiIntersection* arg2) { return {}; }
__attribute__((weak)) void aiGoalFollowWayPts::Init() {}
__attribute__((weak)) void aiGoalFollowWayPts::PlanRoute() {}
__attribute__((weak)) void aiGoalFollowWayPts::SolveTargetPoint() {}
// --- aiGoalStop ---
__attribute__((weak)) void aiGoalStop::Init() {}
// --- aiIntersection ---
__attribute__((weak)) aiPath* aiIntersection::Path(i32 arg1) { return {}; }
// --- aiMap ---
__attribute__((weak)) void aiMap::AllwaysGreen() {}
__attribute__((weak)) void aiMap::AllwaysRed() {}
__attribute__((weak)) i32 aiMap::ChooseNextFreewayLink(aiRailSet* arg1) { return {}; }
__attribute__((weak)) i32 aiMap::ChooseNextLeftStraightLink(aiRailSet* arg1) { return {}; }
__attribute__((weak)) i32 aiMap::ChooseNextRightStraightFreewayLink(aiRailSet* arg1) { return {}; }
__attribute__((weak)) i32 aiMap::ChooseNextRightStraightLink(aiRailSet* arg1) { return {}; }
__attribute__((weak)) i32 aiMap::ChooseNextStraightLink(aiRailSet* arg1) { return {}; }
__attribute__((weak)) void aiMap::Clean() {}
__attribute__((weak)) void aiMap::Cull() {}
// UNPARSED MEMBER: [mmai/aiMap.h] ARTS_IMPORT i32 DetermineOppMapComponent(Matrix34& arg1, aiRailSet* arg2, i16* arg3, i16* arg4, f32* arg5,
__attribute__((weak)) void aiMap::DrawAppRoads() {}
__attribute__((weak)) void aiMap::DrawNextVisibleAmbient() {}
__attribute__((weak)) MetaClass* aiMap::GetClass() { return {}; }
__attribute__((weak)) void aiMap::Init(char* arg1, char* arg2, char* arg3, mmCar* arg4) {}
__attribute__((weak)) void aiMap::Reset() {}
__attribute__((weak)) void aiMap::Update() {}
// --- aiPath ---
__attribute__((weak)) f32 aiPath::CenterLength(i32 arg1, i32 arg2) { return {}; }
__attribute__((weak)) i32 aiPath::Index(Vector3& arg1) { return {}; }
__attribute__((weak)) void aiPath::StopDestinationSources(b32 arg1) {}
// --- aiPedestrianInstance ---
__attribute__((weak)) i32 aiPedestrianInstance::ComputeLod(f32 arg1, f32 arg2) { return {}; }
__attribute__((weak)) void aiPedestrianInstance::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL DrawShadow() override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL FromMatrix(const Matrix34& arg1) override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- aiRailSet ---
__attribute__((weak)) i32 aiRailSet::CalcCopRailPosition(Vector3& arg1, Vector3& arg2, f32 arg3, f32 arg4) { return {}; }
__attribute__((weak)) void aiRailSet::DrawTurn(f32 arg1) {}
__attribute__((weak)) i32 aiRailSet::SolveTurnType(aiPath* arg1, aiPath* arg2) { return {}; }
// --- aiStuck ---
__attribute__((weak)) void aiStuck::Update() {}
// --- aiVehicle ---
__attribute__((weak)) void aiVehicle::Init(i32 arg1) {}
__attribute__((weak)) void aiVehicle::Reset() {}
__attribute__((weak)) void aiVehicle::Update() {}
// --- aiVehicleActive ---
__attribute__((weak)) aiVehicleActive::~aiVehicleActive() {}
__attribute__((weak)) aiVehicleActive::aiVehicleActive() {}
// --- aiVehicleAmbient ---
__attribute__((weak)) void aiVehicleAmbient::Dump() {}
// --- aiVehicleData ---
__attribute__((weak)) aiVehicleData::aiVehicleData() {}
// --- aiVehicleInstance ---
__attribute__((weak)) mmPhysEntity* aiVehicleInstance::AttachEntity() { return {}; }
// UNPARSED MEMBER: [mmai/aiVehicleMGR.h] ARTS_IMPORT void ARTS_FASTCALL DrawGlow() override;
__attribute__((weak)) void aiVehicleInstance::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL DrawShadow() override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL FromMatrix(const Matrix34& arg1) override;
__attribute__((weak)) MetaClass* aiVehicleInstance::GetClass() { return {}; }
__attribute__((weak)) aiVehicleData* aiVehicleInstance::GetData() { return {}; }
__attribute__((weak)) mmPhysEntity* aiVehicleInstance::GetEntity() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
__attribute__((weak)) Vector3 aiVehicleInstance::GetVelocity() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- aiVehicleManager ---
__attribute__((weak)) void aiVehicleManager::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void aiVehicleManager::Detach(aiVehicleActive* arg1) {}
__attribute__((weak)) void aiVehicleManager::Reset() {}
__attribute__((weak)) void aiVehicleManager::Save(Stream* arg1) {}
__attribute__((weak)) i32 aiVehicleManager::Update() { return {}; }
// --- aiVehicleOpponent ---
__attribute__((weak)) void aiVehicleOpponent::AddToAiAudMgr() {}
__attribute__((weak)) void aiVehicleOpponent::AddWidget(Bank* arg1) {}
__attribute__((weak)) void aiVehicleOpponent::Dump() {}
// --- aiVehiclePolice ---
__attribute__((weak)) void aiVehiclePolice::Dump() {}
// --- aiVehicleSpline ---
__attribute__((weak)) void aiVehicleSpline::DrawId() {}
__attribute__((weak)) MetaClass* aiVehicleSpline::GetClass() { return {}; }
__attribute__((weak)) void aiVehicleSpline::Reset() {}
__attribute__((weak)) i32 aiVehicleSpline::Type() { return {}; }
__attribute__((weak)) void aiVehicleSpline::Update() {}
// --- asBenchStats ---
__attribute__((weak)) void asBenchStats::Current(asBenchStats* arg1) {}
__attribute__((weak)) void asBenchStats::Reset() {}
// --- asBirthRule ---
__attribute__((weak)) void asBirthRule::InitSpark(asSparkInfo* arg1, asSparkPos* arg2) {}
// --- asBound ---
__attribute__((weak)) asBound::asBound() {}
// --- asCamera ---
__attribute__((weak)) asCamera::~asCamera() {}
__attribute__((weak)) void asCamera::DrawEnd() {}
__attribute__((weak)) void asCamera::FadeIn(f32 arg1, i32 arg2) {}
__attribute__((weak)) void asCamera::SetUnderlay(aconst char* arg1) {}
__attribute__((weak)) void asCamera::SetViewport(f32 arg1, f32 arg2, f32 arg3, f32 arg4, i32 arg5) {}
__attribute__((weak)) i32 asCamera::Update() { return {}; }
// --- asInertialCS ---
__attribute__((weak)) void asInertialCS::ApplyImpulse(const Vector3& arg1, const Vector3& arg2) {}
__attribute__((weak)) Vector3 asInertialCS::GetVelocity() { return {}; }
__attribute__((weak)) void asInertialCS::MoveICS() {}
__attribute__((weak)) i32 asInertialCS::Update() { return {}; }
__attribute__((weak)) void asInertialCS::Zero() {}
// --- asLamp ---
__attribute__((weak)) void asLamp::AddWidgets(Bank* arg1) {}
__attribute__((weak)) asLamp::asLamp() {}
__attribute__((weak)) void asLamp::Cull(i32 arg1) {}
__attribute__((weak)) MetaClass* asLamp::GetClass() { return {}; }
__attribute__((weak)) void asLamp::SetDistant() {}
__attribute__((weak)) i32 asLamp::Update() { return {}; }
// --- asLineSparks ---
__attribute__((weak)) void asLineSparks::RadialBlast(i32 arg1, Vector3& arg2, Vector3& arg3) {}
// --- asMeshSetForm ---
__attribute__((weak)) asMeshSetForm::asMeshSetForm() {}
__attribute__((weak)) static asMeshSetForm::void(*Lighter)(u8*, u32*, u32*, agiMeshSet*) { return {}; }
__attribute__((weak)) void asMeshSetForm::SetShape(char* arg1, char* arg2, Vector3* arg3, i32 arg4, i32 arg5) {}
__attribute__((weak)) void asMeshSetForm::SetZRead(i32 arg1) {}
__attribute__((weak)) void asMeshSetForm::SetZWrite(i32 arg1) {}
__attribute__((weak)) agiTexDef* asMeshSetForm::SphMapTex {};
// --- asNetObject ---
__attribute__((weak)) asNetObject::asNetObject() {}
__attribute__((weak)) void asNetObject::PositionUpdate(Matrix34* arg1, Vector3 arg2, f32 arg3, f32 arg4, f32 arg5) {}
__attribute__((weak)) i32 asNetObject::Update() { return {}; }
// --- asNetwork ---
__attribute__((weak)) void asNetwork::CloseSession() {}
__attribute__((weak)) void asNetwork::DeallocateStreamObjs() {}
__attribute__((weak)) void asNetwork::Send(ulong arg1, void* arg2, ulong arg3, i32 arg4) {}
// --- asNode ---
__attribute__((weak)) i32 asNode::TimingCount {};
// --- asPortalWeb ---
__attribute__((weak)) asPortalCell* asPortalWeb::AddCell(aconst char* name, asPortalRenderable* render, u32 index) { return {}; }
__attribute__((weak)) asPortalEdge* asPortalWeb::AddEdge(aconst char* name, asPortalCell* cell1, asPortalCell* cell2, i32 num_edges) { return {}; }
// --- asRenderWeb ---
__attribute__((weak)) void asRenderWeb::Cull(i32 arg1) {}
// UNPARSED MEMBER: [mmcity/renderweb.h] ARTS_IMPORT asPortalCell* GetStartCell(
__attribute__((weak)) i32 asRenderWeb::Update() { return {}; }
// --- asSimulation ---
__attribute__((weak)) void asSimulation::Benchmark() {}
// --- mmAmbientAudio ---
__attribute__((weak)) mmAmbientAudio::~mmAmbientAudio() {}
__attribute__((weak)) mmAmbientAudio::mmAmbientAudio(mmPlayer* arg1) {}
// --- mmAnimInstState ---
__attribute__((weak)) i32 mmAnimInstState::FrameDelta {};
__attribute__((weak)) f32 mmAnimInstState::FrameFraction {};
// --- mmAnimMgr ---
__attribute__((weak)) void mmAnimMgr::AirlinerSwap() {}
__attribute__((weak)) i32 mmAnimMgr::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) mmAnimMgr::~mmAnimMgr() {}
__attribute__((weak)) mmAnimMgr::mmAnimMgr() {}
__attribute__((weak)) void mmAnimMgr::UFOSwap() {}
// --- mmAnimTrigger ---
__attribute__((weak)) i32 mmAnimTrigger::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- mmArrow ---
__attribute__((weak)) i32 mmArrow::Update() { return {}; }
// --- mmBangerData ---
__attribute__((weak)) void mmBangerData::LaunchInstance(f32 arg1, Vector3* arg2) {}
// --- mmBangerDataManager ---
__attribute__((weak)) i32 mmBangerDataManager::AddBangerDataEntry(aconst char* banger, aconst char* part) { return {}; }
__attribute__((weak)) agiTexSorter* mmBangerDataManager::Instance {};
// --- mmBangerInstance ---
__attribute__((weak)) i32 mmBangerInstance::ComputeLod(f32 arg1, f32 arg2) { return {}; }
// UNPARSED MEMBER: [mmai/aiVehicleMGR.h] ARTS_IMPORT void ARTS_FASTCALL DrawGlow() override;
__attribute__((weak)) void mmBangerInstance::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL DrawShadow() override;
// --- mmBangerManager ---
__attribute__((weak)) i32 mmBangerManager::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) agiTexSorter* mmBangerManager::Instance {};
// --- mmBoundTemplate ---
__attribute__((weak)) void mmBoundTemplate::AddIndex(i32 arg1, i32 arg2, i32 arg3) {}
__attribute__((weak)) void mmBoundTemplate::AddRef() {}
__attribute__((weak)) void mmBoundTemplate::Collide(Vector3 arg1) {}
__attribute__((weak)) void mmBoundTemplate::DoPageIn() {}
__attribute__((weak)) void mmBoundTemplate::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmdyna/bndtmpl.h] ARTS_IMPORT static RcOwner<mmBoundTemplate> GetBoundTemplate(
__attribute__((weak)) i32 mmBoundTemplate::LockIfResident() { return {}; }
__attribute__((weak)) i32 mmBoundTemplate::Release() { return {}; }
__attribute__((weak)) void mmBoundTemplate::Unlock() {}
__attribute__((weak)) Vector3* mmBoundTemplate::VertPtr {};
// --- mmBridgeMgr ---
__attribute__((weak)) agiTexSorter* mmBridgeMgr::Instance {};
__attribute__((weak)) void mmBridgeMgr::ToggleDrawLabels() {}
// --- mmBridgeSet ---
__attribute__((weak)) i32 mmBridgeSet::ReadEntry(Stream* arg1, i32 arg2) { return {}; }
// --- mmBuildingInstance ---
__attribute__((weak)) MetaClass* mmBuildingInstance::GetClass() { return {}; }
// UNPARSED MEMBER: [mmcity/cullcity.h] ARTS_IMPORT f32 ARTS_FASTCALL GetScale() override;
__attribute__((weak)) usize mmBuildingInstance::SizeOf() { return {}; }
// --- mmCDPlayer ---
__attribute__((weak)) void mmCDPlayer::NextTrack() {}
__attribute__((weak)) void mmCDPlayer::PlayStop() {}
__attribute__((weak)) void mmCDPlayer::PrevTrack() {}
__attribute__((weak)) void mmCDPlayer::Toggle() {}
// --- mmCRHUD ---
__attribute__((weak)) void mmCRHUD::ActivateRosterGold(ulong arg1) {}
// --- mmCar ---
__attribute__((weak)) void mmCar::Init(aconst char* arg1, i32 arg2, i32 arg3) {}
__attribute__((weak)) f32 mmCar::PostUpdateTime {};
__attribute__((weak)) f32 mmCar::TotalUpdateTime {};
__attribute__((weak)) f32 mmCar::UpdateTime {};
// --- mmCarModel ---
__attribute__((weak)) i32 mmCarModel::Activate() { return {}; }
__attribute__((weak)) void mmCarModel::ApplyDamage(Vector3& arg1, f32 arg2) {}
__attribute__((weak)) void mmCarModel::ClearDamage(b32 arg1) {}
__attribute__((weak)) void mmCarModel::Deactivate() {}
__attribute__((weak)) void mmCarModel::Impact(i32 arg1) {}
__attribute__((weak)) i32 mmCarModel::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void mmCarModel::Reset() {}
// --- mmCarSim ---
__attribute__((weak)) void mmCarSim::Explode() {}
__attribute__((weak)) mmCarSim::~mmCarSim() {}
__attribute__((weak)) mmCarSim::mmCarSim() {}
__attribute__((weak)) void mmCarSim::PlayHorn() {}
__attribute__((weak)) void mmCarSim::PlayImpactAudio(i16 arg1, mmIntersection* arg2, Vector3* arg3) {}
__attribute__((weak)) void mmCarSim::ReInit(aconst char* arg1) {}
__attribute__((weak)) void mmCarSim::RemoveNetVehicleAudio() {}
__attribute__((weak)) void mmCarSim::Reset() {}
__attribute__((weak)) void mmCarSim::StartSiren() {}
__attribute__((weak)) void mmCarSim::StopHorn() {}
__attribute__((weak)) void mmCarSim::StopSiren() {}
// --- mmCellRenderer ---
__attribute__((weak)) i32 mmCellRenderer::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) mmCellRenderer::mmCellRenderer() {}
// --- mmCityInfo ---
__attribute__((weak)) b32 mmCityInfo::Load(char* path) { return {}; }
// --- mmCullCity ---
__attribute__((weak)) i16 mmCullCity::GetRoomFlags(i16 arg1) { return {}; }
__attribute__((weak)) void mmCullCity::InitObjectDetail() {}
__attribute__((weak)) void mmCullCity::InitSnowTextures() {}
__attribute__((weak)) void mmCullCity::InitTimeOfDayAndWeather() {}
__attribute__((weak)) agiTexSorter* mmCullCity::Instance {};
__attribute__((weak)) i32 mmCullCity::IsPolyWater(mmPolygon* arg1) { return {}; }
__attribute__((weak)) void mmCullCity::LoadBangers(char* arg1) {}
__attribute__((weak)) void mmCullCity::LoadFacades(char* arg1) {}
__attribute__((weak)) mmCullCity::~mmCullCity() {}
__attribute__((weak)) mmCullCity::mmCullCity() {}
__attribute__((weak)) void mmCullCity::ToggleSky() {}
__attribute__((weak)) void mmCullCity::UpdateSnowTextures() {}
// --- mmDamage ---
__attribute__((weak)) mmDamage::~mmDamage() {}
__attribute__((weak)) mmDamage::mmDamage() {}
// --- mmDofBangerInstance ---
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL FromMatrix(const Matrix34& arg1) override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
__attribute__((weak)) usize mmDofBangerInstance::SizeOf() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- mmDropDown ---
__attribute__((weak)) void mmDropDown::SetDisabledColors() {}
__attribute__((weak)) void mmDropDown::SetString(LocString* arg1) {}
__attribute__((weak)) i32 mmDropDown::Update() { return {}; }
// --- mmEdgeBodyIsect ---
__attribute__((weak)) mmEdgeBodyIsect::mmEdgeBodyIsect() {}
// --- mmFrictionFF ---
__attribute__((weak)) i32 mmFrictionFF::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void mmFrictionFF::Stop() {}
// --- mmGame ---
__attribute__((weak)) void mmGame::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void mmGame::DropThruCityHandler() {}
__attribute__((weak)) i32 mmGame::GetCDTrack(i16 arg1) { return {}; }
__attribute__((weak)) MetaClass* mmGame::GetClass() { return {}; }
__attribute__((weak)) void mmGame::HitWaterHandler() {}
__attribute__((weak)) void mmGame::InitGameStrings() {}
__attribute__((weak)) void mmGame::InitOtherPlayers() {}
__attribute__((weak)) void mmGame::PlayerSetState() {}
__attribute__((weak)) void mmGame::Reset() {}
__attribute__((weak)) void mmGame::SetIconsState() {}
__attribute__((weak)) void mmGame::Update() {}
// --- mmGameManager ---
__attribute__((weak)) agiTexSorter* mmGameManager::Instance {};
__attribute__((weak)) void mmGameManager::LoadReplay(aconst char* arg1) {}
__attribute__((weak)) mmGameManager::~mmGameManager() {}
__attribute__((weak)) mmGameManager::mmGameManager() {}
__attribute__((weak)) void mmGameManager::SaveReplay(aconst char* arg1) {}
__attribute__((weak)) void mmGameManager::StartReplay() {}
// --- mmGameMulti ---
__attribute__((weak)) void mmGameMulti::EnableRacers() {}
__attribute__((weak)) void mmGameMulti::SendMsg(i32 arg1) {}
__attribute__((weak)) void mmGameMulti::UpdateGame() {}
// --- mmGameRecord ---
__attribute__((weak)) void mmGameRecord::DoScan(Vector4& arg1) {}
__attribute__((weak)) void mmGameRecord::Dump() {}
__attribute__((weak)) i32 mmGameRecord::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) mmGameRecord::~mmGameRecord() {}
__attribute__((weak)) mmGameRecord::mmGameRecord(f32 arg1) {}
// --- mmGameSingle ---
__attribute__((weak)) void mmGameSingle::DisableRacers() {}
// --- mmHUD ---
__attribute__((weak)) void mmHUD::ActivateDash() {}
__attribute__((weak)) void mmHUD::DeactivateDash() {}
__attribute__((weak)) void mmHUD::Enable(char* arg1, i16 arg2, i16 arg3) {}
__attribute__((weak)) void mmHUD::GetPosHdg(Vector4& arg1) {}
__attribute__((weak)) i32 mmHUD::IsDashActive() { return {}; }
__attribute__((weak)) mmHUD::~mmHUD() {}
__attribute__((weak)) void mmHUD::PostChatMessage(aconst char* arg1) {}
__attribute__((weak)) void mmHUD::SetMessage(LocString* arg1, f32 time, b32 top = false) {}
__attribute__((weak)) void mmHUD::StopTimers() {}
__attribute__((weak)) void mmHUD::ToggleExternalView() {}
// --- mmHitBangerInstance ---
__attribute__((weak)) void mmHitBangerInstance::Draw(DLP* arg1, i32 arg2) {}
// --- mmHudMap ---
__attribute__((weak)) i32 mmHudMap::Activate() { return {}; }
__attribute__((weak)) void mmHudMap::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void mmHudMap::Cycle() {}
__attribute__((weak)) void mmHudMap::DrawCops() {}
__attribute__((weak)) void mmHudMap::DrawCopsnRobbers() {}
__attribute__((weak)) void mmHudMap::DrawMisc() {}
__attribute__((weak)) void mmHudMap::DrawOrientedBitmap(Matrix34* arg1, agiBitmap* arg2) {}
__attribute__((weak)) void mmHudMap::DrawWaypoints() {}
__attribute__((weak)) MetaClass* mmHudMap::GetClass() { return {}; }
__attribute__((weak)) void mmHudMap::RegisterOpponents(OppIconInfo* arg1, i32 arg2) {}
__attribute__((weak)) void mmHudMap::Reset() {}
__attribute__((weak)) void mmHudMap::SetMode(i32 arg1) {}
__attribute__((weak)) void mmHudMap::ToggleFullScreen() {}
__attribute__((weak)) void mmHudMap::ToggleMapRes() {}
__attribute__((weak)) i32 mmHudMap::Update() { return {}; }
// --- mmIODev ---
__attribute__((weak)) b32 mmIODev::Assign(ilong coeff) { return {}; }
__attribute__((weak)) i32 mmIODev::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- mmIcons ---
__attribute__((weak)) i32 mmIcons::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) mmIcons::~mmIcons() {}
__attribute__((weak)) mmIcons::mmIcons() {}
__attribute__((weak)) void mmIcons::RegisterOpponents(OppIconInfo* arg1, i32 arg2) {}
// --- mmInput ---
__attribute__((weak)) i32 mmInput::AttachToPipe() { return {}; }
__attribute__((weak)) void mmInput::ClearEventHitFlags() {}
__attribute__((weak)) b32 mmInput::DeviceConnected() { return {}; }
__attribute__((weak)) i32 mmInput::DoingFF() { return {}; }
__attribute__((weak)) i32 mmInput::FFPlay(i32 arg1) { return {}; }
__attribute__((weak)) i32 mmInput::FFSetValues(i32 arg1, f32 arg2, f32 arg3) { return {}; }
__attribute__((weak)) f32 mmInput::GetCamPan() { return {}; }
__attribute__((weak)) f32 mmInput::GetSteering() { return {}; }
__attribute__((weak)) f32 mmInput::GetThrottle() { return {}; }
__attribute__((weak)) f32 mmInput::GetThrottleVal() { return {}; }
__attribute__((weak)) b32 mmInput::Init(IDirectInputDevice2A* device) { return {}; }
__attribute__((weak)) b32 mmInput::JoystickHasCoolie() { return {}; }
__attribute__((weak)) mmInput::~mmInput() {}
__attribute__((weak)) mmInput::mmInput() {}
__attribute__((weak)) i32 mmInput::PollStates() { return {}; }
__attribute__((weak)) i32 mmInput::PopEvent(i32* arg1) { return {}; }
__attribute__((weak)) void mmInput::ProcessJoyEvents() {}
__attribute__((weak)) i64 mmInput::ProcessStates() { return {}; }
__attribute__((weak)) void mmInput::PutEventInQueue(i64 arg1) {}
__attribute__((weak)) void mmInput::Reset() {}
__attribute__((weak)) i32 mmInput::ToggleFFEnabled(i32 arg1) { return {}; }
// --- mmInstance ---
__attribute__((weak)) static mmInstance::void(*DynamicLighter)(u8*, u32*, u32*, agiMeshSet*) { return {}; }
__attribute__((weak)) MetaClass* mmInstance::GetClass() { return {}; }
// UNPARSED MEMBER: [mmcity/inst.h] ARTS_IMPORT static i32 GetMeshSetSet(aconst char* name, i32 mesh_flags, aconst char* part, Vector3* offset);
// --- mmInterface ---
__attribute__((weak)) void mmInterface::BeDone() {}
__attribute__((weak)) MetaClass* mmInterface::GetClass() { return {}; }
__attribute__((weak)) void mmInterface::MessageCallback2(void* arg1, void* arg2) {}
__attribute__((weak)) void mmInterface::MessageCallback(void* arg1, void* arg2) {}
__attribute__((weak)) mmInterface::mmInterface() {}
__attribute__((weak)) void mmInterface::Reset() {}
__attribute__((weak)) void mmInterface::SetupArchiveTest(i32& arg1) {}
__attribute__((weak)) void mmInterface::ShowMain(i32 arg1) {}
__attribute__((weak)) i32 mmInterface::Update() { return {}; }
// --- mmIntersection ---
__attribute__((weak)) void mmIntersection::InitSegment(const Vector3& arg1, const Vector3& arg2, mmBoundTemplate* arg3, i32 arg4, i32 arg5) {}
__attribute__((weak)) mmIntersection::mmIntersection() {}
__attribute__((weak)) void mmIntersection::Transform(Matrix34* arg1) {}
// --- mmJaxis ---
__attribute__((weak)) i32 mmJaxis::Capture() { return {}; }
__attribute__((weak)) mmJaxis::mmJaxis() {}
__attribute__((weak)) void mmJaxis::Normalize(f32 arg1) {}
__attribute__((weak)) void mmJaxis::NormalizePOV(ulong arg1) {}
// --- mmLoader ---
__attribute__((weak)) void mmLoader::BeginTask(LocString* arg1, f32 arg2 = 0.0f) {}
__attribute__((weak)) void mmLoader::Current(asBenchStats* arg1) {}
__attribute__((weak)) void mmLoader::EndTask(f32 arg1 = 0.0f) {}
__attribute__((weak)) mmLoader::~mmLoader() {}
__attribute__((weak)) mmLoader::mmLoader() {}
__attribute__((weak)) void mmLoader::Reset() {}
__attribute__((weak)) void mmLoader::SetIntroText(LocString* arg1) {}
// --- mmMatrixInstance ---
__attribute__((weak)) MetaClass* mmMatrixInstance::GetClass() { return {}; }
// --- mmMiscData ---
__attribute__((weak)) mmMiscData::~mmMiscData() {}
__attribute__((weak)) mmMiscData::mmMiscData() {}
// --- mmMultiCR ---
__attribute__((weak)) void mmMultiCR::DropGold(Vector3 arg1, i32 arg2) {}
__attribute__((weak)) void mmMultiCR::FillResults() {}
__attribute__((weak)) void mmMultiCR::FondleCarMass(mmCar* arg1, f32 arg2) {}
__attribute__((weak)) void mmMultiCR::UpdateBank() {}
__attribute__((weak)) void mmMultiCR::UpdateGold() {}
__attribute__((weak)) void mmMultiCR::UpdateHideout() {}
__attribute__((weak)) void mmMultiCR::UpdateHUD() {}
__attribute__((weak)) void mmMultiCR::UpdateLimit() {}
__attribute__((weak)) void mmMultiCR::UpdateTimeWarning() {}
// --- mmPhysExec ---
__attribute__((weak)) void mmPhysExec::DoUpdateAll() {}
__attribute__((weak)) void mmPhysExec::DoUpdatePlayerOnly() {}
// --- mmPhysicsMGR ---
__attribute__((weak)) void mmPhysicsMGR::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void mmPhysicsMGR::Collide(Vector3 arg1) {}
__attribute__((weak)) void mmPhysicsMGR::Cull(i32 arg1) {}
__attribute__((weak)) i32 mmPhysicsMGR::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) agiTexSorter* mmPhysicsMGR::Instance {};
__attribute__((weak)) void mmPhysicsMGR::Reset() {}
__attribute__((weak)) void mmPhysicsMGR::Shutdown() {}
__attribute__((weak)) i32 mmPhysicsMGR::Update() { return {}; }
__attribute__((weak)) void mmPhysicsMGR::UpdatePaused() {}
// --- mmPlayer ---
__attribute__((weak)) void mmPlayer::EnableRegen(i32 arg1) {}
__attribute__((weak)) i32 mmPlayer::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) i32 mmPlayer::IsMaxDamaged() { return {}; }
__attribute__((weak)) i32 mmPlayer::IsPOV() { return {}; }
__attribute__((weak)) void mmPlayer::ResetDamage() {}
__attribute__((weak)) void mmPlayer::SetCamInterest(asInertialCS* arg1) {}
__attribute__((weak)) void mmPlayer::SetPreRaceCam() {}
__attribute__((weak)) void mmPlayer::SetWideFOV(b32 arg1) {}
__attribute__((weak)) void mmPlayer::ToggleCam() {}
__attribute__((weak)) void mmPlayer::ToggleDash() {}
__attribute__((weak)) void mmPlayer::ToggleExternalView() {}
__attribute__((weak)) void mmPlayer::ToggleWideFOV() {}
// --- mmPlayerCarAudio ---
__attribute__((weak)) void mmPlayerCarAudio::StartSiren() {}
__attribute__((weak)) void mmPlayerCarAudio::StopSiren() {}
// --- mmPlayerConfig ---
__attribute__((weak)) void mmPlayerConfig::GetAudio() {}
__attribute__((weak)) void mmPlayerConfig::GetControls() {}
__attribute__((weak)) void mmPlayerConfig::GetGraphics() {}
__attribute__((weak)) void mmPlayerConfig::GetViewSettings() {}
__attribute__((weak)) mmPlayerConfig::~mmPlayerConfig() {}
__attribute__((weak)) mmPlayerConfig::mmPlayerConfig() {}
__attribute__((weak)) void mmPlayerConfig::Save(Stream* arg1) {}
// --- mmPlayerData ---
__attribute__((weak)) i32 mmPlayerData::GetBlitzPassed() { return {}; }
__attribute__((weak)) i32 mmPlayerData::GetCheckpointPassed() { return {}; }
__attribute__((weak)) i32 mmPlayerData::GetCircuitPassed() { return {}; }
__attribute__((weak)) char* mmPlayerData::GetFileName() { return {}; }
__attribute__((weak)) i32 mmPlayerData::GetTotalPassed() { return {}; }
__attribute__((weak)) i32 mmPlayerData::GetTotalScore() { return {}; }
// --- mmPlayerDirectory ---
__attribute__((weak)) mmPlayerDirectory::mmPlayerDirectory() {}
__attribute__((weak)) mmPlayerDirectory::~mmPlayerDirectory() {}
// --- mmPolygon ---
__attribute__((weak)) void mmPolygon::PlotTriangle(i32 arg1, i32 arg2, i32 arg3, mmBoundTemplate* arg4, i32 arg5) {}
// --- mmPopup ---
__attribute__((weak)) mmPopup::mmPopup(mmGame* arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5) {}
__attribute__((weak)) void mmPopup::ProcessChat() {}
__attribute__((weak)) void mmPopup::ProcessEscape(i32 arg1) {}
__attribute__((weak)) void mmPopup::ProcessKeymap(i32 arg1) {}
__attribute__((weak)) void mmPopup::RecordPosition(aconst char* arg1) {}
__attribute__((weak)) void mmPopup::Reset() {}
__attribute__((weak)) void mmPopup::ShowResults() {}
__attribute__((weak)) void mmPopup::ShowRoster() {}
__attribute__((weak)) i32 mmPopup::Update() { return {}; }
// --- mmPositions ---
__attribute__((weak)) i32 mmPositions::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void mmPositions::Load(Stream* arg1) {}
__attribute__((weak)) mmPositions::mmPositions() {}
__attribute__((weak)) i32 mmPositions::Recall(i32 arg1, Matrix34* arg2, i32* arg3, char* arg4) { return {}; }
// UNPARSED MEMBER: [mmcamtour/gamerecord.h] ARTS_IMPORT i32 Register(
// --- mmRaceData ---
__attribute__((weak)) void mmRaceData::Load(Stream* arg1) {}
__attribute__((weak)) mmRaceData::mmRaceData() {}
// --- mmRunwayLight ---
__attribute__((weak)) void mmRunwayLight::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
// UNPARSED MEMBER: [mmcity/cullcity.h] ARTS_IMPORT f32 ARTS_FASTCALL GetScale() override;
__attribute__((weak)) mmRunwayLight::mmRunwayLight(aconst char* arg1, Vector3& arg2, Vector3& arg3) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- mmShard ---
__attribute__((weak)) MetaClass* mmShard::GetClass() { return {}; }
// --- mmShardManager ---
__attribute__((weak)) void mmShardManager::AddWidgets(Bank* arg1) {}
__attribute__((weak)) void mmShardManager::EmitShards(Vector3 arg1, f32 arg2, f32 arg3) {}
__attribute__((weak)) MetaClass* mmShardManager::GetClass() { return {}; }
__attribute__((weak)) i32 mmShardManager::NumInstances {};
__attribute__((weak)) i32 mmShardManager::Update() { return {}; }
// --- mmSingleCircuit ---
__attribute__((weak)) void mmSingleCircuit::DisableRacers() {}
// --- mmSkid ---
__attribute__((weak)) void mmSkid::Draw(DLP* arg1, i32 arg2) {}
__attribute__((weak)) MetaClass* mmSkid::GetClass() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- mmSkidManager ---
__attribute__((weak)) void mmSkidManager::LayTrack() {}
__attribute__((weak)) mmSkidManager::~mmSkidManager() {}
__attribute__((weak)) mmSkidManager::mmSkidManager() {}
__attribute__((weak)) void mmSkidManager::ReInit(aconst char* arg1) {}
__attribute__((weak)) void mmSkidManager::Reset() {}
// --- mmSky ---
__attribute__((weak)) i32 mmSky::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
// --- mmSplash ---
__attribute__((weak)) i32 mmSplash::Activate() { return {}; }
__attribute__((weak)) void mmSplash::Reset() {}
// --- mmSpringFF ---
__attribute__((weak)) i32 mmSpringFF::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void mmSpringFF::Stop() {}
// --- mmStaticInstance ---
__attribute__((weak)) usize mmStaticInstance::SizeOf() { return {}; }
// --- mmTextNode ---
__attribute__((weak)) i32 mmTextNode::AddText(void* font, LocString* text, i32 effects, f32 x, f32 y) { return {}; }
__attribute__((weak)) i32 mmTextNode::Update() { return {}; }
// --- mmTrailer ---
__attribute__((weak)) i32 mmTrailer::Activate() { return {}; }
__attribute__((weak)) void mmTrailer::Deactivate() {}
__attribute__((weak)) i32 mmTrailer::Init(char* arg1, char* arg2, Vector3* arg3) { return {}; }
__attribute__((weak)) void mmTrailer::PostUpdate() {}
__attribute__((weak)) void mmTrailer::Reset() {}
__attribute__((weak)) void mmTrailer::SetHackedImpactParams() {}
// --- mmTrailerInstance ---
__attribute__((weak)) mmPhysEntity* mmTrailerInstance::AttachEntity() { return {}; }
__attribute__((weak)) void mmTrailerInstance::Draw(DLP* arg1, i32 arg2) {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL DrawShadow() override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL FromMatrix(const Matrix34& arg1) override;
__attribute__((weak)) mmPhysEntity* mmTrailerInstance::GetEntity() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
__attribute__((weak)) Vector3 mmTrailerInstance::GetVelocity() { return {}; }
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- mmTransmission ---
__attribute__((weak)) void mmTransmission::Automatic(i32 arg1) {}
__attribute__((weak)) i32 mmTransmission::Downshift() { return {}; }
__attribute__((weak)) i32 mmTransmission::GetCurrentGear() { return {}; }
__attribute__((weak)) i32 mmTransmission::SetCurrentGear(i32 arg1) { return {}; }
__attribute__((weak)) void mmTransmission::SetDrive() {}
__attribute__((weak)) void mmTransmission::SetReverse() {}
__attribute__((weak)) i32 mmTransmission::Upshift() { return {}; }
// --- mmUnhitBangerInstance ---
__attribute__((weak)) void mmUnhitBangerInstance::InitBreakables(aconst char* name, aconst char* part, mmBangerData* bng_data) {}
__attribute__((weak)) void mmUnhitBangerInstance::Reset() {}
// --- mmVehInfo ---
__attribute__((weak)) void mmVehInfo::Load(Stream* arg1) {}
__attribute__((weak)) mmVehInfo::mmVehInfo() {}
__attribute__((weak)) void mmVehInfo::Print(Stream* arg1) {}
// --- mmVehicleForm ---
__attribute__((weak)) void mmVehicleForm::Cull(i32 arg1) {}
__attribute__((weak)) agiTexDef* mmVehicleForm::SphMapTex {};
// --- mmViewCS ---
__attribute__((weak)) MetaClass* mmViewCS::GetClass() { return {}; }
__attribute__((weak)) void mmViewCS::Reset() {}
__attribute__((weak)) i32 mmViewCS::Update() { return {}; }
// --- mmVoiceCommentary ---
__attribute__((weak)) mmVoiceCommentary::mmVoiceCommentary() {}
__attribute__((weak)) void mmVoiceCommentary::PlayCRPreRace() {}
__attribute__((weak)) void mmVoiceCommentary::PlayCR(i16 arg1, i16 arg2) {}
__attribute__((weak)) void mmVoiceCommentary::PlayPreRace() {}
__attribute__((weak)) void mmVoiceCommentary::PlayRoam() {}
__attribute__((weak)) void mmVoiceCommentary::PlayTimePenalty() {}
__attribute__((weak)) void mmVoiceCommentary::SetFrequency(f32 arg1) {}
__attribute__((weak)) void mmVoiceCommentary::StopNow() {}
__attribute__((weak)) void mmVoiceCommentary::ValidateCity(char* arg1) {}
// --- mmWaypointInstance ---
__attribute__((weak)) i32 mmWaypointInstance::ComputeLod(f32 arg1, f32 arg2) { return {}; }
__attribute__((weak)) void mmWaypointInstance::Draw(DLP* arg1, i32 arg2) {}
__attribute__((weak)) MetaClass* mmWaypointInstance::GetClass() { return {}; }
// UNPARSED MEMBER: [mmcity/cullcity.h] ARTS_IMPORT f32 ARTS_FASTCALL GetScale() override;
// --- mmWaypoints ---
__attribute__((weak)) void mmWaypoints::GetClosestWaypoint() {}
// --- mmWheel ---
__attribute__((weak)) f32 mmWheel::PtxMaxSkidCount {};
// --- mmYInstance ---
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT void ARTS_FASTCALL FromMatrix(const Matrix34& arg1) override;
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Vector3& ARTS_FASTCALL GetPos() override;
__attribute__((weak)) mmYInstance::mmYInstance() {}
// UNPARSED MEMBER: [mmai/aiPedestrian.h] ARTS_IMPORT Matrix34& ARTS_FASTCALL ToMatrix(Matrix34& arg1) override;
// --- sfPointer ---
__attribute__((weak)) void sfPointer::Cull(i32 arg1) {}
__attribute__((weak)) MetaClass* sfPointer::GetClass() { return {}; }
__attribute__((weak)) i32 sfPointer::Update() { return {}; }
// --- string ---
__attribute__((weak)) i32 string::NumSubStrings() { return {}; }
// UNPARSED MEMBER: [data7/str.h] ARTS_IMPORT void operator+=(char arg1);
// UNPARSED MEMBER: [agi/lmodel.h] ARTS_IMPORT void operator=(const agiLightModelParameters& arg1);
__attribute__((weak)) void string::SaveName(const string& arg1, i32 arg2, const string& arg3, const string& arg4) {}
__attribute__((weak)) string string::SubString(i32 arg1) { return {}; }
// === Vtable Stubs ===
// vtables are automatically emitted when their first non-pure virtual function is defined
// The member stubs above should provide those definitions

#pragma GCC diagnostic pop